# Generated by Django 5.0.3 on 2024-04-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
