# Generated by Django 5.0.3 on 2024-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_delete_payment_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoney',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
    ]
