# Generated by Django 5.0.3 on 2024-04-19 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_usermoney_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoney',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_money', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermoney',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=11),
        ),
    ]
