# Generated by Django 5.0.3 on 2024-04-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_usermoney_user_alter_usermoney_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoney',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=10),
        ),
    ]
