# Generated by Django 5.0.3 on 2024-04-19 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfrom', models.CharField(max_length=100)),
                ('userto', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('payment', models.DecimalField(decimal_places=4, default=0, max_digits=11)),
                ('currency', models.CharField(choices=[('G', 'GB Pounds'), ('U', 'US Dollars'), ('E', 'Euros')], max_length=1)),
                ('dat', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfrom', models.CharField(max_length=100)),
                ('userto', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('payment', models.DecimalField(decimal_places=4, default=0, max_digits=11)),
                ('currency', models.CharField(choices=[('G', 'GB Pounds'), ('U', 'US Dollars'), ('E', 'Euros')], max_length=1)),
                ('dat', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
