# Generated by Django 5.0.3 on 2024-04-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='done',
        ),
        migrations.RemoveField(
            model_name='request',
            name='done',
        ),
    ]
