# Generated by Django 5.0.3 on 2024-04-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
